INSERT into Attraction(AttractionName, Descreption, LocationId)
VALUES
('Vikingskipshuset','På detta museum hittar du fantastiska samlingar av fynd från vikingatiden. Det är gravfynd som gjordes under slutet av 1800-talet och början av 1900-talet som innehåller alltifrån skepp till redskap och vapen från vikingatiden. Två vikingaskepp från 800-talet som är bland världens bäst bevarade finns på museet.',2),
('Slottsparken', 'Slottsparken i Oslo är helt öppen för allmänheten och ett besök här passar perfekt för den som vill få en paus från asfalt och betong och istället få strosa runt bland träd och buskage. Som besökare kan man även få se vaktavlösningen på slottet som sker varje dag efter lunch. Tittar man på vaktavlösningen ska man lägga märkte till ifall musik spelas eller inte. Det är nämligen som så att ifall musik spelas så är kungen hemma i slottet. Framför slottet kan man även se en staty av Kung Karl Johan som styrde Sverige och Norge från 1818 till 1844.',2),
('Holmenkollen','Holmenkollen är en toppmodern hoppbacke som ligger i ett villaområde med samma namn nordväst om Oslo. Detta är en oerhört populär turistattraktion som besöks av uppåt 1 miljon människor varje år. Vid Holmenkollen hittar man även världens äldsta skidmuseum där man kan uppleva 4000 år av skidhistoria. Hela området ligger på runt 350 meter över havet vilket gör att man kan få en mycket vacker panoramautsikt över Oslo',2),
('Segway Tours Copenhagen', 'Upplev Köpenhamn på ett helt unikt sätt genom att färdas på segway genom staden. Attraktionen på två hjul ger dig bland annat möjlighet att se Nyhavn, Den Lille Havfrue, Operaen och Amalienborg.',3),
(' Christiania', 'Idag en av Danmarks mest kända turistattraktioner.  Christiania ligger i Christianshavn och grundades 1971 av ockupanter som tog gamla baracker i besittning och förvandlade dem till sina hem',3),
('Marienplatz', 'Münchens hjärta ligger vid Marienplatz. Här finns också rådhuset där det världsberömda klockspelet kan höras varje dag klockan 11.00 och 12.00. Benstarka personer kan gå upp i det 85 meter höga rådhustornet och blicka ut över staden.',8),
('Engelska trädgården', 'En promenad i den engelska trädgården bjuder på 200 års grönskande ängar. Mitt i trädgården ligger det spektakulära kinesiska tornet. Många passar på att ta en välbehövlig paus i ölträdgården nedanför.',8),
('Chokladmuseum', 'Le musée du chocolat är ett 800 kvadratmeter stort museum helt tillägnat choklad. Alla besökare får med sig 100 gram smaskig choklad innan de går hem. Du hittar chokladmuseet på Parc de la Porte Sud, rue du Pont du Péage.',9),
('La Petite France', ' Den lilla stadsdelen La Petite France är den mest romantiska och mysigaste delen av Strasbourg. Här står riktiga timmerhus uppradade och Rhens biflod Ill bidrar till den pittoreska stämningen för omkringströvande besökare. Bland de medeltida byggnaderna finns också gott om trevliga restauranger. Härifrån kan du åka på guidade turer längs flodkrökarna. Turerna tar 70 minuter och ges på flera olika språk. Du når La Petite France från Place du marché aux poissons.',9),
('Main Tower', 'Under år 2000 blev tornet Main Tower färdigställt och är idag en mycket populär turistattraktion i Tyskland. Tornet är en imponerande skyskrapa med hela 200 metes höjd. Det finns totalt 56 våningar och har ett visningsobservatorium längst upp, där man kan se hela staden',10),
('Alter Oper', 'Alter Oper är ett mycket vackert operahus, som dock förstördes under andra världskriget. Man har återskapat fasaden med dess renässansstil, men är modernt inuti. Det finns en mycket härlig restaurang med uteterrass på tredje våningen, där man kan avnjuta god mat och dryck med en fantastisk vy.',10)